export const APP_ROUTES = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  NEW_VERIFICATION: "/auth/new-verification",
  NEW_PASSWORD: "/auth/new-password",
  TWO_FACTOR: "/auth/two-factor",
  RESET_PASSWORD: "/auth/reset-password",
  AUTH_ERROR: "/auth/error",
  LOGOUT: "/auth/logout",
  HOME_PAGE: "/feedback",
  CREATE_FEEDBACK: "/feedback/create",
  FEEDBACK_DETAIL: "/feedback/[feedbackId]",
  EDIT_FEEDBACK: "/feedback/[feedbackId]/edit",
  ROADMAP: "/feedback/roadmap",
};
